<?php

/**
 * BaseOrdemServicoEquipamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idEquipamento
 * @property integer $idOrdemServico
 * @property OrdemServico $OrdemServico
 * @property Equipamento $Equipamento
 * 
 * @method integer                 getIdEquipamento()  Returns the current record's "idEquipamento" value
 * @method integer                 getIdOrdemServico() Returns the current record's "idOrdemServico" value
 * @method OrdemServico            getOrdemServico()   Returns the current record's "OrdemServico" value
 * @method Equipamento             getEquipamento()    Returns the current record's "Equipamento" value
 * @method OrdemServicoEquipamento setIdEquipamento()  Sets the current record's "idEquipamento" value
 * @method OrdemServicoEquipamento setIdOrdemServico() Sets the current record's "idOrdemServico" value
 * @method OrdemServicoEquipamento setOrdemServico()   Sets the current record's "OrdemServico" value
 * @method OrdemServicoEquipamento setEquipamento()    Sets the current record's "Equipamento" value
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdemServicoEquipamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ordem_servico_equipamento');
        $this->hasColumn('idEquipamento', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idOrdemServico', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OrdemServico', array(
             'local' => 'idOrdemServico',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Equipamento', array(
             'local' => 'idEquipamento',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}