<?php

/**
 * BaseObservacaoOrdemServico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property string $observacao
 * @property integer $idOrdemServico
 * @property OrdemServico $OrdemServico
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer                getIdUsuario()      Returns the current record's "idUsuario" value
 * @method string                 getObservacao()     Returns the current record's "observacao" value
 * @method integer                getIdOrdemServico() Returns the current record's "idOrdemServico" value
 * @method OrdemServico           getOrdemServico()   Returns the current record's "OrdemServico" value
 * @method sfGuardUser            getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method ObservacaoOrdemServico setIdUsuario()      Sets the current record's "idUsuario" value
 * @method ObservacaoOrdemServico setObservacao()     Sets the current record's "observacao" value
 * @method ObservacaoOrdemServico setIdOrdemServico() Sets the current record's "idOrdemServico" value
 * @method ObservacaoOrdemServico setOrdemServico()   Sets the current record's "OrdemServico" value
 * @method ObservacaoOrdemServico setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObservacaoOrdemServico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('observacao_ordem_servico');
        $this->hasColumn('idUsuario', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('observacao', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('idOrdemServico', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OrdemServico', array(
             'local' => 'idOrdemServico',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'idUsuario',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}