<?php

/**
 * BaseComponente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $descricao
 * @property decimal $preco
 * @property Doctrine_Collection $PrecosComponente
 * @property Doctrine_Collection $ComponentesOrdem
 * @property Doctrine_Collection $ComponentesOrdemServico
 * 
 * @method string              getNome()                    Returns the current record's "nome" value
 * @method string              getDescricao()               Returns the current record's "descricao" value
 * @method decimal             getPreco()                   Returns the current record's "preco" value
 * @method Doctrine_Collection getPrecosComponente()        Returns the current record's "PrecosComponente" collection
 * @method Doctrine_Collection getComponentesOrdem()        Returns the current record's "ComponentesOrdem" collection
 * @method Doctrine_Collection getComponentesOrdemServico() Returns the current record's "ComponentesOrdemServico" collection
 * @method Componente          setNome()                    Sets the current record's "nome" value
 * @method Componente          setDescricao()               Sets the current record's "descricao" value
 * @method Componente          setPreco()                   Sets the current record's "preco" value
 * @method Componente          setPrecosComponente()        Sets the current record's "PrecosComponente" collection
 * @method Componente          setComponentesOrdem()        Sets the current record's "ComponentesOrdem" collection
 * @method Componente          setComponentesOrdemServico() Sets the current record's "ComponentesOrdemServico" collection
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComponente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('componente');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('preco', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PrecoComponente as PrecosComponente', array(
             'local' => 'id',
             'foreign' => 'idComponente'));

        $this->hasMany('OrdemServico as ComponentesOrdem', array(
             'refClass' => 'ComponenteOrdemServico',
             'local' => 'idComponente',
             'foreign' => 'id'));

        $this->hasMany('ComponenteOrdemServico as ComponentesOrdemServico', array(
             'local' => 'id',
             'foreign' => 'idComponente'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}