<?php

/**
 * BasePais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $sigla
 * @property Doctrine_Collection $PaisEstados
 * 
 * @method string              getNome()        Returns the current record's "nome" value
 * @method string              getSigla()       Returns the current record's "sigla" value
 * @method Doctrine_Collection getPaisEstados() Returns the current record's "PaisEstados" collection
 * @method Pais                setNome()        Sets the current record's "nome" value
 * @method Pais                setSigla()       Sets the current record's "sigla" value
 * @method Pais                setPaisEstados() Sets the current record's "PaisEstados" collection
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pais');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('sigla', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estado as PaisEstados', array(
             'local' => 'id',
             'foreign' => 'idPais'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}