<?php

/**
 * BaseServicoOrdemServico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idOrdemServico
 * @property integer $idServico
 * @property integer $quantidade
 * @property OrdemServico $OrdemServico
 * @property Servico $Servico
 * 
 * @method integer             getIdOrdemServico() Returns the current record's "idOrdemServico" value
 * @method integer             getIdServico()      Returns the current record's "idServico" value
 * @method integer             getQuantidade()     Returns the current record's "quantidade" value
 * @method OrdemServico        getOrdemServico()   Returns the current record's "OrdemServico" value
 * @method Servico             getServico()        Returns the current record's "Servico" value
 * @method ServicoOrdemServico setIdOrdemServico() Sets the current record's "idOrdemServico" value
 * @method ServicoOrdemServico setIdServico()      Sets the current record's "idServico" value
 * @method ServicoOrdemServico setQuantidade()     Sets the current record's "quantidade" value
 * @method ServicoOrdemServico setOrdemServico()   Sets the current record's "OrdemServico" value
 * @method ServicoOrdemServico setServico()        Sets the current record's "Servico" value
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicoOrdemServico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servico_ordem_servico');
        $this->hasColumn('idOrdemServico', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idServico', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quantidade', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OrdemServico', array(
             'local' => 'idOrdemServico',
             'foreign' => 'id'));

        $this->hasOne('Servico', array(
             'local' => 'idServico',
             'foreign' => 'id'));
    }
}