<?php

/**
 * BaseEquipamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $descricao
 * @property integer $idTipoEquipamento
 * @property integer $idCliente
 * @property Cliente $Cliente
 * @property TipoEquipamento $TipoEquipamento
 * @property Doctrine_Collection $OrdemServicoEquipamento
 * 
 * @method string              getNome()                    Returns the current record's "nome" value
 * @method string              getDescricao()               Returns the current record's "descricao" value
 * @method integer             getIdTipoEquipamento()       Returns the current record's "idTipoEquipamento" value
 * @method integer             getIdCliente()               Returns the current record's "idCliente" value
 * @method Cliente             getCliente()                 Returns the current record's "Cliente" value
 * @method TipoEquipamento     getTipoEquipamento()         Returns the current record's "TipoEquipamento" value
 * @method Doctrine_Collection getOrdemServicoEquipamento() Returns the current record's "OrdemServicoEquipamento" collection
 * @method Equipamento         setNome()                    Sets the current record's "nome" value
 * @method Equipamento         setDescricao()               Sets the current record's "descricao" value
 * @method Equipamento         setIdTipoEquipamento()       Sets the current record's "idTipoEquipamento" value
 * @method Equipamento         setIdCliente()               Sets the current record's "idCliente" value
 * @method Equipamento         setCliente()                 Sets the current record's "Cliente" value
 * @method Equipamento         setTipoEquipamento()         Sets the current record's "TipoEquipamento" value
 * @method Equipamento         setOrdemServicoEquipamento() Sets the current record's "OrdemServicoEquipamento" collection
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipamento');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('idTipoEquipamento', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('idCliente', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'idCliente',
             'foreign' => 'id'));

        $this->hasOne('TipoEquipamento', array(
             'local' => 'idTipoEquipamento',
             'foreign' => 'id'));

        $this->hasMany('OrdemServico as OrdemServicoEquipamento', array(
             'local' => 'idEquipamento',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}