<?php

/**
 * BaseTipoEquipamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $descricao
 * @property Doctrine_Collection $TipoEquipamentoEquipamentos
 * 
 * @method string              getNome()                        Returns the current record's "nome" value
 * @method string              getDescricao()                   Returns the current record's "descricao" value
 * @method Doctrine_Collection getTipoEquipamentoEquipamentos() Returns the current record's "TipoEquipamentoEquipamentos" collection
 * @method TipoEquipamento     setNome()                        Sets the current record's "nome" value
 * @method TipoEquipamento     setDescricao()                   Sets the current record's "descricao" value
 * @method TipoEquipamento     setTipoEquipamentoEquipamentos() Sets the current record's "TipoEquipamentoEquipamentos" collection
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoEquipamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_equipamento');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Equipamento as TipoEquipamentoEquipamentos', array(
             'local' => 'id',
             'foreign' => 'idTipoEquipamento'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}