<?php

/**
 * BaseComponenteOrdemServico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idOrdemServico
 * @property integer $idComponente
 * @property integer $quantidade
 * @property OrdemServico $OrdemServico
 * @property Componente $Componente
 * 
 * @method integer                getIdOrdemServico() Returns the current record's "idOrdemServico" value
 * @method integer                getIdComponente()   Returns the current record's "idComponente" value
 * @method integer                getQuantidade()     Returns the current record's "quantidade" value
 * @method OrdemServico           getOrdemServico()   Returns the current record's "OrdemServico" value
 * @method Componente             getComponente()     Returns the current record's "Componente" value
 * @method ComponenteOrdemServico setIdOrdemServico() Sets the current record's "idOrdemServico" value
 * @method ComponenteOrdemServico setIdComponente()   Sets the current record's "idComponente" value
 * @method ComponenteOrdemServico setQuantidade()     Sets the current record's "quantidade" value
 * @method ComponenteOrdemServico setOrdemServico()   Sets the current record's "OrdemServico" value
 * @method ComponenteOrdemServico setComponente()     Sets the current record's "Componente" value
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComponenteOrdemServico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('componente_ordem_servico');
        $this->hasColumn('idOrdemServico', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idComponente', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quantidade', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OrdemServico', array(
             'local' => 'idOrdemServico',
             'foreign' => 'id'));

        $this->hasOne('Componente', array(
             'local' => 'idComponente',
             'foreign' => 'id'));
    }
}