<?php

/**
 * BaseOrdemServico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idCliente
 * @property integer $idEquipamento
 * @property enum $status
 * @property string $descricao_problema
 * @property Cliente $Cliente
 * @property Equipamento $Equipamento
 * @property Doctrine_Collection $Servicos
 * @property Doctrine_Collection $Componentes
 * @property Doctrine_Collection $ServicosOrdemServico
 * @property Doctrine_Collection $ComponentesOrdemServico
 * 
 * @method integer             getIdCliente()               Returns the current record's "idCliente" value
 * @method integer             getIdEquipamento()           Returns the current record's "idEquipamento" value
 * @method enum                getStatus()                  Returns the current record's "status" value
 * @method string              getDescricaoProblema()       Returns the current record's "descricao_problema" value
 * @method Cliente             getCliente()                 Returns the current record's "Cliente" value
 * @method Equipamento         getEquipamento()             Returns the current record's "Equipamento" value
 * @method Doctrine_Collection getServicos()                Returns the current record's "Servicos" collection
 * @method Doctrine_Collection getComponentes()             Returns the current record's "Componentes" collection
 * @method Doctrine_Collection getServicosOrdemServico()    Returns the current record's "ServicosOrdemServico" collection
 * @method Doctrine_Collection getComponentesOrdemServico() Returns the current record's "ComponentesOrdemServico" collection
 * @method OrdemServico        setIdCliente()               Sets the current record's "idCliente" value
 * @method OrdemServico        setIdEquipamento()           Sets the current record's "idEquipamento" value
 * @method OrdemServico        setStatus()                  Sets the current record's "status" value
 * @method OrdemServico        setDescricaoProblema()       Sets the current record's "descricao_problema" value
 * @method OrdemServico        setCliente()                 Sets the current record's "Cliente" value
 * @method OrdemServico        setEquipamento()             Sets the current record's "Equipamento" value
 * @method OrdemServico        setServicos()                Sets the current record's "Servicos" collection
 * @method OrdemServico        setComponentes()             Sets the current record's "Componentes" collection
 * @method OrdemServico        setServicosOrdemServico()    Sets the current record's "ServicosOrdemServico" collection
 * @method OrdemServico        setComponentesOrdemServico() Sets the current record's "ComponentesOrdemServico" collection
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdemServico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ordem_servico');
        $this->hasColumn('idCliente', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('idEquipamento', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'default' => 'Em Aberto',
             'values' => 
             array(
              0 => 'Em aberto',
              1 => 'Em execução',
              2 => 'Pendente',
              3 => 'Cancelado',
              4 => 'Concluído',
             ),
             ));
        $this->hasColumn('descricao_problema', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'idCliente',
             'foreign' => 'id'));

        $this->hasOne('Equipamento', array(
             'local' => 'id',
             'foreign' => 'idEquipamento'));

        $this->hasMany('Servico as Servicos', array(
             'refClass' => 'ServicoOrdemServico',
             'local' => 'id',
             'foreign' => 'idServico'));

        $this->hasMany('Componente as Componentes', array(
             'refClass' => 'ComponenteOrdemServico',
             'local' => 'id',
             'foreign' => 'idComponente'));

        $this->hasMany('ServicoOrdemServico as ServicosOrdemServico', array(
             'local' => 'id',
             'foreign' => 'idOrdemServico'));

        $this->hasMany('ComponenteOrdemServico as ComponentesOrdemServico', array(
             'local' => 'id',
             'foreign' => 'idOrdemServico'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}