<?php

/**
 * BaseEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $sigla
 * @property integer $idPais
 * @property Pais $Pais
 * @property Doctrine_Collection $EstadoCidades
 * 
 * @method string              getNome()          Returns the current record's "nome" value
 * @method string              getSigla()         Returns the current record's "sigla" value
 * @method integer             getIdPais()        Returns the current record's "idPais" value
 * @method Pais                getPais()          Returns the current record's "Pais" value
 * @method Doctrine_Collection getEstadoCidades() Returns the current record's "EstadoCidades" collection
 * @method Estado              setNome()          Sets the current record's "nome" value
 * @method Estado              setSigla()         Sets the current record's "sigla" value
 * @method Estado              setIdPais()        Sets the current record's "idPais" value
 * @method Estado              setPais()          Sets the current record's "Pais" value
 * @method Estado              setEstadoCidades() Sets the current record's "EstadoCidades" collection
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('sigla', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('idPais', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pais', array(
             'local' => 'idPais',
             'foreign' => 'id'));

        $this->hasMany('Cidade as EstadoCidades', array(
             'local' => 'id',
             'foreign' => 'idEstado'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}