<?php

/**
 * BaseServico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $descricao
 * @property decimal $preco
 * @property Doctrine_Collection $PrecosServico
 * @property Doctrine_Collection $ServicosOrdem
 * @property Doctrine_Collection $ServicosOrdemServico
 * 
 * @method string              getNome()                 Returns the current record's "nome" value
 * @method string              getDescricao()            Returns the current record's "descricao" value
 * @method decimal             getPreco()                Returns the current record's "preco" value
 * @method Doctrine_Collection getPrecosServico()        Returns the current record's "PrecosServico" collection
 * @method Doctrine_Collection getServicosOrdem()        Returns the current record's "ServicosOrdem" collection
 * @method Doctrine_Collection getServicosOrdemServico() Returns the current record's "ServicosOrdemServico" collection
 * @method Servico             setNome()                 Sets the current record's "nome" value
 * @method Servico             setDescricao()            Sets the current record's "descricao" value
 * @method Servico             setPreco()                Sets the current record's "preco" value
 * @method Servico             setPrecosServico()        Sets the current record's "PrecosServico" collection
 * @method Servico             setServicosOrdem()        Sets the current record's "ServicosOrdem" collection
 * @method Servico             setServicosOrdemServico() Sets the current record's "ServicosOrdemServico" collection
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servico');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('preco', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PrecoServico as PrecosServico', array(
             'local' => 'id',
             'foreign' => 'idServico'));

        $this->hasMany('OrdemServico as ServicosOrdem', array(
             'refClass' => 'ServicoOrdemServico',
             'local' => 'idServico',
             'foreign' => 'id'));

        $this->hasMany('ServicoOrdemServico as ServicosOrdemServico', array(
             'local' => 'id',
             'foreign' => 'idServico'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}