solicitacao:
  class: sfDoctrineRouteCollection
  options:
    model:                Solicitacao
    module:               solicitacao
    prefix_path:          /solicitacao
    column:               id
    with_wildcard_routes: true

ordem_servico_ordemSevico:
  class: sfDoctrineRouteCollection
  options:
    model:                OrdemServico
    module:               ordemSevico
    prefix_path:          /ordemSevico
    column:               id
    with_wildcard_routes: true

status:
  class: sfDoctrineRouteCollection
  options:
    model:                Status
    module:               status
    prefix_path:          /Status
    column:               id
    with_wildcard_routes: true

ordem_servico:
  class: sfDoctrineRouteCollection
  options:
    model:                OrdemServico
    module:               ordemServico
    prefix_path:          /ordemServico
    column:               id
    with_wildcard_routes: true

componente:
  class: sfDoctrineRouteCollection
  options:
    model:                Componente
    module:               componente
    prefix_path:          /componente
    column:               id
    with_wildcard_routes: true

servico:
  class: sfDoctrineRouteCollection
  options:
    model:                Servico
    module:               servico
    prefix_path:          /servico
    column:               id
    with_wildcard_routes: true

ordem_servico_equipamento_cliente:
  url: /ordemServico/equipamentoCliente
  params:
    module: ordemServico
    action: EquipamentosCliente

equipamento:
  class: sfDoctrineRouteCollection
  options:
    model:                Equipamento
    module:               equipamento
    prefix_path:          /equipamento
    column:               id
    with_wildcard_routes: true

tipo_equipamento:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoEquipamento
    module:               tipoEquipamento
    prefix_path:          /tipoEquipamento
    column:               id
    with_wildcard_routes: true

cliente:
  class: sfDoctrineRouteCollection
  options:
    model:                Cliente
    module:               cliente
    prefix_path:          /cliente
    column:               id
    with_wildcard_routes: true

pais:
  class: sfDoctrineRouteCollection
  options:
    model:                Pais
    module:               pais
    prefix_path:          /pais
    column:               id
    with_wildcard_routes: true



cidade:
  class: sfDoctrineRouteCollection
  options:
    model:                cidade
    module:               cidade
    prefix_path:          /cidade
    column:               id
    with_wildcard_routes: true

estado:
  class: sfDoctrineRouteCollection
  options:
    model:                Estado
    module:               estado
    prefix_path:          /estado
    column:               id
    with_wildcard_routes: true

usuario:
  class: sfDoctrineRouteCollection
  options:
    model:                Usuario
    module:               usuario
    prefix_path:          /usuario
    column:               id
    with_wildcard_routes: true

# Rotas Personalisadas para ajax
ordemServico_equipamentosCliente:
  url: /ordemServico/changeCliente
  params:
    module: ordemServico
    action: changeCliente


ordemServico_adicionaServico:
  url: /ordemServico/addServico
  params:
    module: ordemServico
    action: addServicoOS

ordemServico_removeServico:
  url: /ordemServico/remServico
  params:
    module: ordemServico
    action: remServicoOS

ordemServico_adicionaComponente:
  url: /ordemServico/addComponente
  params:
    module: ordemServico
    action: addComponenteOS

ordemServico_removeComponente:
  url: /ordemServico/remComponente
  params:
    module: ordemServico
    action: remComponenteOS

ordemServico_pesquisaServico:
  url: /ordemServico/pesquisaServico
  params:
    module: ordemServico
    action: pesquisaServico

ordemServico_pesquisaComponente:
  url: /ordemServico/pesquisaComponente
  params:
    module: ordemServico
    action: pesquisaComponente

# Rotas para as solicitações feitas pelo site
solicitacao_newOS:
  url:      /solicitacao/newOS/:id
  class:    sfDoctrineRoute
  options:  { model: Solicitacao, type: object }
  param:    { module: solicitacao, action: newOS}
  requirements:
    id: \d+
    sf_method: [post]


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: ordemServico, action: index }



# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
