generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TipoEquipamento
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tipo_equipamento
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        created_at: { label: Criado em }
        updated_at: { label: Atualizado em }
      actions: ~
      fields:  ~
      list:
        title: Lista de Tipos de Equipamento
        display: [nome, descricao]
      filter:
        display: [nome, descricao]
      form:    ~
      edit:
        title: Editando %%nome%%
        actions: {_save: {label: Salvar}, _list: {label: voltar}, _delete: {label: Excluir}}
      new:
        title: Novo Tipo de Equipamento
        actions: {_save: {label: Salvar}, _list: {label: voltar}}