<?php

/**
 * Cliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cliente extends BaseCliente
{
    public function  __toString() {
        return $this->getNome();
    }

    public function save(Doctrine_Connection $conn = null){

        if($this->isNew())
            $this->setCreatedAt(date('Y-m-d H:i:s'));
        else{
            $this->setCreatedAt($this->getCreatedAt());
            $this->setUpdatedAt(date('Y-m-d H:i:s'));
        }
        return parent::save($conn);
    }
}