<?php

/**
 * OrdemServico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OrdemServico extends BaseOrdemServico
{


}