<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/17 17:13:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sgos',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
