<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/17 17:28:40
sfConfig::add(array(
  'mod_tipoequipamento_enabled' => true,
  'mod_tipoequipamento_view_class' => 'sfPHP',
));
