<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/12 17:41:23
sfConfig::add(array(
  'mod_tipoequipamento_enabled' => true,
  'mod_tipoequipamento_view_class' => 'sfPHP',
));
