<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/16 19:28:50
sfConfig::add(array(
  'mod_tipoequipamento_enabled' => true,
  'mod_tipoequipamento_view_class' => 'sfPHP',
));
