<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/05/17 17:30:45
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'funcionario',
      ),
    ),
  ),
);
