<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/21 21:11:45
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
