<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/05/17 17:30:19
$this->security = array (
  'update' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'funcionario',
    ),
  ),
  'save' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'funcionario',
    ),
  ),
  'delete' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'funcionario',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'funcionario',
        2 => 'cliente',
      ),
    ),
  ),
);
