<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/22 20:57:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sgos_sgos',
  'username' => 'sgos',
  'password' => 'ik6yh651',
  'name' => 'doctrine',
)),);
