generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Componente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          componente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at: {label: Criado em}
      list:
        title: Lista de Componentes
        display: [nome, descricao, preco]
      filter:
        display: [nome, descricao, preco, created_at]
      form:
        display: [nome, descricao, preco]
      edit:
        title: Editando - %%nome%%
        actions: {_save: {label: salvar}, _list: {label: voltar}, _delete: {label: excluir}}
      new:
        title: Novo Componente
        actions: {_save: {label: Salvar}, _list: {label: Voltar}}
