generator:
  class: sfDoctrineGenerator
  param:
    model_class:           cidade
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cidade
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        nome: {label: Nome}
        idEstado: {label: Estado}
        display: [=nome, =estado]
      list:
        title: Lista de Cidades
        display: [nome, estado]
      filter:
        display: [nome, idEstado]
      form:    ~
      edit:
        title: Editando %%nome%%
        actions: {_save: {label: Salvar}, _list: {label: voltar}, _delete: {label: Excluir}}
      new:
        title: Nova Cidade
        actions: {_save: {label: Salvar}, _list: {label: voltar}}
