<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('observacao_ordem_servico', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'idusuario' => 
             array(
              'type' => 'int',
              'notnull' => '1',
              'length' => '',
             ),
             'observacao' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '4000',
             ),
             'idordemservico' => 
             array(
              'type' => 'int',
              'notnull' => '1',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('observacao_ordem_servico');
    }
}