generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Servico
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          servico
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        preco: { label: Preço }
        created_at: {label: Cadastrado em}
      list:
        title: Lista de Serviços
        display: [nome, descricao, preco]
      filter:
        display: [nome, descricao, preco, created_at]
      form:
        display: [nome, descricao, preco]
      edit:
        title: Editando - %%nome%%
        actions: {_save: {label: salvar}, _list: {label: voltar}, _delete: {label: excluir}}
      new:
        title: Novo Serviço
        actions: {_save: {label: salvar}, _list: {label: voltar}}