<?php

/**
 * Componente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sgos
 * @subpackage model
 * @author     Wellington Wagner
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Componente extends BaseComponente
{

    public function save(Doctrine_Connection $conn = null){

        $conn = parent::save($conn);

        $precoComponente = new PrecoComponente();
        $precoComponente->setPreco($this->getPreco());
        $precoComponente->setDataInicio(date('Y-m-d H:i:s'));
        $precoComponente->setIdComponente($this->getId());

        $precoComponente->save();

        return $conn;

    }

}