<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('servico_ordem_servico', 'servico_ordem_servico_id_ordem_servico_id', array(
             'name' => 'servico_ordem_servico_id_ordem_servico_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'ordem_servico',
             ));
        $this->addIndex('servico_ordem_servico', 'servico_ordem_servico_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('servico_ordem_servico', 'servico_ordem_servico_id_ordem_servico_id');
        $this->removeIndex('servico_ordem_servico', 'servico_ordem_servico_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}