<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('observacao_ordem_servico', 'observacao_ordem_servico_idordemservico_ordem_servico_id', array(
             'name' => 'observacao_ordem_servico_idordemservico_ordem_servico_id',
             'local' => 'idordemservico',
             'foreign' => 'id',
             'foreignTable' => 'ordem_servico',
             ));
        $this->createForeignKey('observacao_ordem_servico', 'observacao_ordem_servico_idusuario_sf_guard_user_id', array(
             'name' => 'observacao_ordem_servico_idusuario_sf_guard_user_id',
             'local' => 'idusuario',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('observacao_ordem_servico', 'observacao_ordem_servico_idordemservico', array(
             'fields' => 
             array(
              0 => 'idordemservico',
             ),
             ));
        $this->addIndex('observacao_ordem_servico', 'observacao_ordem_servico_idusuario', array(
             'fields' => 
             array(
              0 => 'idusuario',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('observacao_ordem_servico', 'observacao_ordem_servico_idordemservico_ordem_servico_id');
        $this->dropForeignKey('observacao_ordem_servico', 'observacao_ordem_servico_idusuario_sf_guard_user_id');
        $this->removeIndex('observacao_ordem_servico', 'observacao_ordem_servico_idordemservico', array(
             'fields' => 
             array(
              0 => 'idordemservico',
             ),
             ));
        $this->removeIndex('observacao_ordem_servico', 'observacao_ordem_servico_idusuario', array(
             'fields' => 
             array(
              0 => 'idusuario',
             ),
             ));
    }
}