<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('cliente', 'cliente_idusuario_sf_guard_user_id', array(
             'name' => 'cliente_idusuario_sf_guard_user_id',
             'local' => 'idusuario',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('cliente', 'cliente_idusuario', array(
             'fields' => 
             array(
              0 => 'idusuario',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('cliente', 'cliente_idusuario_sf_guard_user_id');
        $this->removeIndex('cliente', 'cliente_idusuario', array(
             'fields' => 
             array(
              0 => 'idusuario',
             ),
             ));
    }
}