<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('cliente', 'idusuario', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('cliente', 'idusuario');
    }
}