generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Pais
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pais
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Lista de Paises
        display: [=nome, =sigla]
      filter:
        display: [nome, sigla]
      form:    ~
      edit:
        title: Editando %%nome%%
        actions: {_save: { label: Salvar }, _list: { label: voltar }, _delete: { label: excluir}}
      new:
        actions: { _save: { label: Salvar}, _list: { label: voltar} }
