generator:
  class: sfDoctrineGenerator
  param:
    model_class:           cliente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:  ~
      actions: 
      fields:  ~
      list:
        title: Lista de Clientes
        layout: stacked
        display: [ =nome, =email, =telefoneResidencial, =telefoneComercial, =cidade ]
      filter:
        display: [ nome, email, logradouro, numero, bairro, idCidade,  created_at]
      form:    ~
      edit:
        title: Editando - %%nome%%
        display: [nome, email, logradouro, numero, complemento, bairro, idCidade, telefoneResidencial, telefoneComercial]
        actions: {_save: {label: Salvar}, _list: {label: Voltar}, _delete: {label: Excluir}}
      new:
        title: Nome Cliente
        display: [nome, email, logradouro, numero, complemento, bairro, idCidade, telefoneResidencial, telefoneComercial]
        actions: {_save: {label: Salvar}, _list: {label: Voltar}}
