generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrdemServico
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ordem_servico
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _save:{ credentials: admi }
      fields:
        id: {label: N. OS}
        created_at: {label: Criado em}
        idCliente: {label: Cliente}
        status: {label: Status}
        equipamentos_ordem_servico_list: {label: Equipamentos }
      list:
        title: Lista de Ordem de Servico
        display: [id, cliente, equipamento]
      filter:
        display: [status, created_at]
      form: ~
        #display: [descricao, idCliente]
      edit:
        title: Editando Ordem de Serviço
        actions: {_save: {label: alterar}, _list: {label: voltar}, _delete: {label: excluir}}
      new:
        title: Nova Ordem de Serviço
        actions: {_save: {label: salvar}, _list: {label: voltar}}