generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrdemServico
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          ordem_servico
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        idCliente: {label: Cliente}
        idEquipamento: {label: Equipamento}
        created_at: {label: Cadastrado em}
        updated_at: {label: Atualizado em}
        servicos: {label: Serviços}
      list:    ~
      filter:  
        display: [idCliente, status, descricao_problema]
      form:    ~
      edit:    ~
      new:     ~
