<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/27 14:03:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sgos',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
