Pais:
  actAs: { Timestampable: ~ }
  columns:
    nome: { type: string(255), notnull: true, unique: true }
    sigla: { type: string(255), notnull: true, unique: true }

Estado:
  actAs: { Timestampable: ~ }
  columns:
    nome: { type: string(255), notnull: true, unique: true }
    sigla: { type: string(4), notnull: true }
    idPais: { type: integer, notnull: true }
  relations:
    Pais:
      local: idPais
      foreign: id
      foreignAlias: PaisEstados

Cidade:
  actAs: { Timestampable: ~}
  columns:
    nome: { type: string(255), notnull: true, unique: true }
    idEstado: {type: integer, notnull: true }
  relations:
    Estado:
      local: idEstado
      foreign: id
      foreignAlias: EstadoCidades

Cliente:
  actAs: {Timestampable: ~}
  columns:
    nome: { type: string(255), notnull: true}
    logradouro: {type: string(255)}
    numero: {type: string(255)}
    complemento: {type: string(255)}
    bairro: {type: string(255)}
    idCidade: {type: integer}
    telefoneResidencial: {type: string(20)}
    telefoneComercial: {type: string(20)}
    email: { type: string(255) }
  relations:
    Cidade:
      local: idCidade
      foreign: id
      foreignAlias: CidadeClientes


TipoEquipamento:
  actAs: { Timestampable: ~ }
  columns:
    nome: { type: string(255), notnull: true, unique:true}
    descricao: { type: string(500)}
  

Equipamento:
  actAs: { Timestampable: ~ }
  columns:
    nome: { type: string(255), notnull: true }
    descricao: { type: string(500)}
    idTipoEquipamento: { type: integer }
    idCliente: { type: integer }
  relations:
    Cliente:
      local: idCliente
      foreign: id
      foreignAlias: ClienteEquipamentos
    TipoEquipamento:
      local: idTipoEquipamento
      foreign: id
      foreignAlias: TipoEquipamentoEquipamentos

Servico:
  actAs: {Timestampable: ~}
  columns:
    nome: {type: string(255), notnull:true, unique:true }
    descricao: { type: string(500), notnull:true }
    preco: {type: decimal, scale: 2}

PrecoServico:
  actAs: {Timestampable: ~}
  columns:
    preco: {type: decimal, scale: 2}
    dataInicio: {type: timestamp}
    idServico: {type: integer, notnull:true}
  relations:
    Servico:
      local: idServico
      foreign: id
      foreignAlias: PrecosServico

Componente:
  actAs: {Timestampable: ~}
  columns:
    nome: {type: string(255), notnull: true, unique: true }
    descricao: { type: string(500), notnull:true }
    preco: {type: decimal, scale: 2}

PrecoComponente:
  actAs: {Timestampable: ~}
  columns:
    preco: {type: decimal, scale: 2}
    dataInicio: {type: timestamp}
    idComponente: {type: integer, notnull: true}
  relations:
    Componente:
      local: idComponente
      foreign: id
      foreignAlias: PrecosComponente

OrdemServico:
  actAs: [Timestampable]
  columns:
    idCliente: {type: integer}
    idEquipamento: {type: integer}
    status: { type: enum, default: Em Aberto, values: [Em aberto, Em execução, Pendente, Cancelado, Concluído]}
    descricao_problema: {type: string(4000)}
  relations:
    Cliente:
      local: idCliente
      foreign: id
      foreignAlias: OrdensServicoCliente
    Equipamento:
      local: id
      foreign: idEquipamento
      foreignAlias: OrdemServicoEquipamentos
    Servicos:
      local: id
      foreign: idServico
      foreignAlias: ServicosOrdem
      class: Servico
      refClass: ServicoOrdemServico
    Componentes:
      local: id
      foreign: idComponente
      foreignAlias: ComponentesOrdem
      class: Componente
      refClass: ComponenteOrdemServico
    Solicitacao:
      local: id
      foreign: idOrdemServico
      foreignAlias: OrdemServicoSolicitacao

ServicoOrdemServico:
  columns:
    idOrdemServico: {type: integer, notnull: true}
    idServico: {type: integer, notnull: true}
    quantidade: {type: integer}
  relations:
    OrdemServico:
      local: idOrdemServico
      foreign: id
      foreignAlias: ServicosOrdemServico
    Servico:
      local: idServico
      foreign: id
      foreignAlias: ServicosOrdemServico

ComponenteOrdemServico:
  columns:
    idOrdemServico: {type: integer, notnull: true}
    idComponente: {type: integer, notnull: true}
    quantidade: {type:  integer}
  relations:
    OrdemServico:
      local: idOrdemServico
      foreign: id
      foreignAlias: ComponentesOrdemServico
    Componente:
      local: idComponente
      foreign: id
      foreignAlias: ComponentesOrdemServico

Solicitacao:
  actAs: {Timestampable: ~}
  columns:
    nome: { type: string(100), notnull: true }
    email: { type: string(100), notnull: true }
    telefone1: {type: string(14), notnull: true }
    telefone2: { type: string(14) }
    descricao_problema: { type: string(500), notnull: true }
    idOrdemServico: { type: integer}
  relations:
    OrdemServico:
      local: idOrdemServico
      foreign: id
      foreignAlias: SolicitacaoOrdemServico

Status:
  actAs: [Timestampable]
  columns:
    nome: {type: string(50), notnull: true}
    significado: {type: string(4000)}